### ISSUE TITLE
Regarding your madness

### ISSUE THREAD

**Issue by biswajitcs** [rajamalw/opencv-android-gradle#1]
Go ahead......What you are thinking about your codes??

**Comment by rhonyabdullah** [comment]
Hello man @biswajitcs , i found [this article](https://www.learn2crack.com/2016/03/setup-opencv-sdk-android-studio.html) which is guide me to this repo. My question, is that article still usable ? I get confused after reading this [opencv website](https://opencv.org/platforms/android/) about where to start using opencv in android studio to build an android apps. Also i found [this](http://blog.codeonion.com/2015/11/25/creating-a-new-opencv-project-in-android-studio/)

**Comment by rajamalw** [comment]
@rhonyabdullah You can use both the articles. It is still usable.
